name: Process GIF

on:
  workflow_dispatch:


jobs:
  process-gif:
    permissions:
      contents: write
      actions: write    # Add this line to grant permission to trigger workflows
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Process the GIF
      - name: Process GIF
        run: |
          echo "Processing GIF..."
          # Comando para processar o GIF
          echo "GIF processed successfully!"

      # Step 3: Trigger next execution
      - name: Trigger Next Run
        run: |
          echo "Re-triggering workflow..."
          gh workflow run "Process GIF"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
